import '../models/currency.dart';

class BuildSummaryGenerator {
  const BuildSummaryGenerator({
    required this.currency,
    required this.totalUsd,
    required this.convertedTotal,
    required this.componentPrices,
    required this.cpuTdpText,
    required this.gpuTdpText,
    required this.recommendedPsu,
  });

  final Currency currency;
  final double totalUsd;
  final double convertedTotal;
  final Map<String, double> componentPrices;
  final String cpuTdpText;
  final String gpuTdpText;
  final int recommendedPsu;

  /// Generates a formatted ASCII summary.
  /// This function is intentionally verbose because the formatted string
  /// is shown in multiple places (copy-to-clipboard, share, etc.).
  String build() {
    final buffer = StringBuffer();
    final dateTime = DateTime.now();
    buffer
      ..writeln('═══════════════════════════════════════')
      ..writeln('   PC BUILD SUMMARY')
      ..writeln('═══════════════════════════════════════')
      ..writeln(
          'Date: ${dateTime.day}/${dateTime.month}/${dateTime.year} ${dateTime.hour}:${dateTime.minute.toString().padLeft(2, '0')}')
      ..writeln('Currency: ${currency.code} (${currency.name})')
      ..writeln('')
      ..writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
      ..writeln('COMPONENT PRICES:')
      ..writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

    componentPrices.forEach((name, price) {
      if (price > 0) {
        buffer.writeln(
            '${name.padRight(15)}: ${currency.symbol}${price.toStringAsFixed(2)}');
      }
    });

    buffer
      ..writeln('')
      ..writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
      ..writeln('TOTAL BUILD COST:')
      ..writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
      ..writeln('${currency.symbol}${convertedTotal.toStringAsFixed(2)}');

    if (currency.code != 'USD') {
      buffer.writeln('(USD Equivalent: \$${totalUsd.toStringAsFixed(2)})');
    }

    final hasTdp = cpuTdpText.isNotEmpty || gpuTdpText.isNotEmpty;
    if (hasTdp || recommendedPsu > 0) {
      buffer
        ..writeln('')
        ..writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
        ..writeln('POWER REQUIREMENTS:')
        ..writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

      if (cpuTdpText.isNotEmpty) buffer.writeln('CPU TDP: ${cpuTdpText}W');
      if (gpuTdpText.isNotEmpty) buffer.writeln('GPU TDP: ${gpuTdpText}W');

      if (recommendedPsu > 0) {
        buffer
          ..writeln('')
          ..writeln('Recommended PSU: ${recommendedPsu}W');
      }
    }

    buffer
      ..writeln('')
      ..writeln('═══════════════════════════════════════')
      ..writeln('Generated by PC Builder')
      ..writeln('═══════════════════════════════════════');

    return buffer.toString();
  }
}
